import './globals.css'
import { Inter } from 'next/font/google'
import Swal from 'sweetalert2'

const inter = Inter({ subsets: ['latin'] })
export const apiURL = (route) => {
  return "http://localhost:3000/api/"+route;
}

export const Toast = Swal.mixin({
  toast: true,
  position: 'bottom-end',
  showConfirmButton: false,
  timer: 3000,
  timerProgressBar: true,
  didOpen: (toast) => {
    toast.addEventListener('mouseenter', Swal.stopTimer)
    toast.addEventListener('mouseleave', Swal.resumeTimer)
  }
})

export const Toaster = (title, status) => {
  Toast.fire({
    icon: status,
    title: title
  })
}

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
